### ISSUE TITLE
Functionaliteit bepalen

### ISSUE THREAD

**Issue by DVDdisk7** [Mijn-Rooster/mijnrooster#1]
Wat moet het kunnen?

**Comment by rreinoutt** [comment]
Functionaliteiten die het ontwerp moet hebben:

- Rooster moet zichtbaar zijn (Eigen rooster en rooster docenten)
- Inlog systeem (schoolpas / wachtwoord)
- overzichtelijke layout
- Touchscreen / keyboard & mouse
- Duidelijke zichbaarheid van veranderingen (lokaal/docentwijziging & uitval)

**Comment by DVDdisk7** [comment]
Het systeem moet:
- werken op elk apparaat met een USB RFID-reader
- automatisch te updaten zijn
- een touchscreen hebben voor bediening
- hufterproef zijn

Een beheerder moet:
- een koppeling kunnen maken met Zermelo d.m.v. een token
- een apparaat kunnen toevoegen met een koppelcode om toegang te geven tot de API -> Het mag niet zo zijn dat iedereen kan praten met onze API en zo maar toegang krijgt tot alle roosters
- het apparaat kunnen beheren via dashboard
- (eventueel) het systeem kunnen customizen met eigen achtergrond, kleuren en logo

De gebruiker moet:
- het rooster kunnen bekijken door in te loggen met zijn/haar schoolpas
- het rooster per dag kunnen bekijken
- roosterwijzigingen in een opslag kunnen zien in het rooster
- (eventueel) kunnen inschrijven voor lessen (zoals werken in de aula)
- (eventueel) het rooster van een docent/medeleerling kunnen opzoeken
- kunnen uitloggen of het systeem logt uit na X aantal seconden inactiviteit?

**Comment by DVDdisk7** [comment]
See https://github.com/Mijn-Rooster/mijnrooster/wiki/Requirements for more details.
