### ISSUE TITLE
Eerste ontwerpen nabouwen in de frontend (niet functioneel)

### ISSUE THREAD

**Issue by DVDdisk7** [Mijn-Rooster/mijnrooster#10]
Probeer de ontwerpen na te bouwen in onze applicatie met html en css.
Het hoeft nog niet functioneel te zijn.
Probeer een beetje bekend te worden met electron en svelte door er mee te spelen.

**Comment by DVDdisk7** [comment]
Ik heb een branch aangemaakt waar je in kan bouwen. 

```
git fetch origin
git checkout 10-eerste-ontwerpen-nabouwen-in-de-frontend-niet-functioneel
```

Makkelijkste is een github codespace aanmaken op deze branch, maar dan moet je ff github education fixen.
Als je vragen hebt moet je maar ff laten weten want dan laat ik wel ff zien hoe het werkt.

**Comment by DVDdisk7** [comment]
ik heb in https://github.com/Mijn-Rooster/mijnrooster/wiki/Development:-codespace uitgelegd hoe je een codespace kan aanmaken en kan openen.

In https://github.com/Mijn-Rooster/mijnrooster/wiki/Development:-frontend staat al wat over hoe de frontend in elkaar zit en hier staat al een stukje beschreven over git: https://github.com/Mijn-Rooster/mijnrooster/wiki/Development:-projects-and-issues

**Comment by DVDdisk7** [comment]
HTML code staat in `temp` folder. Probeer het nu eens om te zetten in Svelte bestanden en kijk of je ook flowbite componenten kan gebruiken (https://flowbite-svelte.com/docs/components/accordion).

Je kan pagina's toevoegen in `frontend/src/renderer/src/routes`. Daar staan nu wat voorbeeld dingetjes, kijk maar of je het een beetje begrijpt hoe het werkt. Het navigeren van pagina's werkt via een router. Om een route (naar je pagina) toe te voegen moet je deze toevoegen aan de `const routes` in `frontend/src/renderer/src/components/Router.svelte`.

Daar staat nu bijvoorbeeld:
```
...

    import Home from '../routes/Home.svelte'; <-- Hier link je dus naar je pagina
    import Test from '../routes/Test.svelte';
    import Login from '../routes/Login.svelte';

...

    const routes = { <-- Hier zeg je welke url bij welke pagina hoort
        '/': Home,
        '/login': Login,
        '/test': Test,
    };

...
````

Om gebruik te maken van navigatie doe je het volgende op je pagina:

```
<script>
...
  import { navigate } from "../stores/RouterStore";
...
</script>

...

<!-- Voorbeeld van een link element waarbij als je er op klikt, deze redirect naar de pagina test -->
    <a target="_blank" rel="noreferrer" on:click={() => navigate("/test")}
      >Go to test page</a
    >
...
````

Kijk eens of je hier verder mee komt?

**Comment by rreinoutt** [comment]
@DVDdisk7 Had jij toen je het ontwerp maakte nou ook een ontwerp voor het weekoverzicht? Want die kan ik nu nergens vinden

**Comment by DVDdisk7** [comment]
Nee volgens mij niet, we zouden daar nu nog een ontwerp voor kunnen maken, kunnen we ook later doen. Dan sluiten we nu eerst deze af.
