### ISSUE TITLE
Design ontwerpen

### ISSUE THREAD

**Issue by DVDdisk7** [Mijn-Rooster/mijnrooster#2]
Het ontwerpen in PP op basis van functionaliteit

**Comment by rreinoutt** [comment]
Ben begonnen met een design voor het uiterlijk van het rooster. Ik ben er zelf nog niet helemaal tevreden mee maar het is een begin. (Zie het bestand.) Feedback is welkom!

[Mijn-rooster design.pptx](https://github.com/user-attachments/files/16872138/Mijn-rooster.design.pptx)

**Comment by DVDdisk7** [comment]
Ik heb ook een ontwerpje gemaakt. Misschien dat we die een beetje kunnen combineren?
[Ontwerp.pptx](https://github.com/user-attachments/files/16873515/Ontwerp.pptx)

**Comment by rreinoutt** [comment]
Veel beter gast! Ik zat veel te moeilijk te denken haha

**Comment by rreinoutt** [comment]
[Ontwerp v2.pptx](https://github.com/user-attachments/files/16995869/Ontwerp.v2.pptx)

https://driestarwartburg-my.sharepoint.com/:p:/g/personal/546028_ll_driestarwartburg_nl/Ebs5A4fg2qFAuHUnG9rGHgMBTFPusw2oSEKKX33Azf8jyA?e=tyHI6L
